# Start with a basic lightweight image
FROM alpine:latest

# Command to print the flag when the container is run
CMD ["sh", "-c", "echo 'ZmxhZ3tpX3VzZWRfZG9ja2VyX3J1bn0K' | base64 -d; while true; do sleep 3600; done"]

LABEL secret="flag{i_used_docker_inspect}"