services:
  ctfd-185:
    #build: .
    image: ctfd/ctfd:latest
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@mariadb-185/ctfd
      - REDIS_URL=redis://redis-185:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - /data/ctfd/CTFd/logs:/var/log/CTFd
      - /data/ctfd/CTFd/uploads:/var/uploads
    depends_on:
      - mariadb-185
    networks:
        default:
        internal:

  nginx-185:
    image: nginx:stable
    restart: always
    ports:
      - 80:80
    depends_on:
      - ctfd-185

  mariadb-185:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /data/ctfd/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  redis-185:
    image: redis:4
    restart: always
    volumes:
    - /data/ctfd/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
